object Main extends App {
  
  //Chapter 1
  //here the questions will be shown in comments and if answer are litterals, they wil be printed into a variable using println function
  println("Chapter 1");
  println("         ");
  println("jdk (Java Development Kit) is a Kit that provides the environment to develop and execute(run) the Java program. " +
    "JDK is a kit(or package) that includes two things: Development Tools(to provide an environment to develop your java programs) " +
    "and JRE (to execute your java program)");

  println("jre is an installation package that provides an environment to only run(not develop) the java program(or " +
    "application)onto your machine. JRE is only used by those who only want to run Java programs that are end-users of your system.");

  println("jvm is  is a very important part of both JDK and JRE because it is contained or inbuilt in both.  Whatever Java " +
    "program you run using JRE or JDK goes into JVM and JVM is responsible for executing the java program line by line, hence it is also " +
    "known as an interpreter.");

  println("byte code can be defined as an intermediate code generated by the compiler after the compilation of source " +
    "code(JAVA Program). This intermediate code makes Java a platform-independent language. ");

  println("Scala was created with the goal of realizing a high-performance and highly concurrent language that " +
    "combines the strength of the following two leading programming patterns on the Java Virtual Machine (JVM) platform: Object-oriented " +
    "programming; Functional programming");

  val aLittebitAboutApacheSpark = println("Apache Spark is a data processing framework that can quickly perform processing tasks on very " +
    "large data sets, and can also distribute data processing tasks across multiple computers, either on its own or in tandem with other " +
    "distributed computing tools. These two qualities are key to the worlds of big data and machine learning, which require the marshalling of " +
    "massive computing power to crunch through large data stores. Spark also takes some of the programming burdens of these tasks off the " +
    "shoulders of developers with an easy-to-use API that abstracts away much of the grunt work of distributed computing and big data processing.");
  
  println("we have: Log analytics, E-commerce personalization, Recommendation engines, Automated candidate placement in " +
    "recruiting, Insurance fraud detection, Relevancy and retention boost for online publishing...");

  println("We can have: Data pipelines, Microservices, Video transcoding systems, Real-time information processing," +
    "Ad-serving, Data processing, Communications platforms, Big data projects, It can be used in amalgamation with Java...");
  
  println("Apache Spark; CScalding (By Twitter); Apache Kafka; Apache Samza; Finagle; Akka; ADAM; Lichess...");

  println("Python is today one the most used programming language in  the world. It is applied in Ai, web, mobile, functionnal programming," +
    "... It is an interpreted language and because of that it is too much slow in front of the compiled languages such as java ans Scala.");
  

  println("");
  println("CHAPTER 2");
  printl("    ");
  println("Those exercises were made in command shell");

}